services:
  nuola-mieter-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuola-mieter-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - nuola-mieter-dashboard-data:/app/data
      - nuola-mieter-dashboard-uploads:/app/public/uploads

volumes:
  nuola-mieter-dashboard-data:
  nuola-mieter-dashboard-uploads:
